.TH "GROUP-1/src/LandBasedWheeled/landbasedwheeled.h" 3 "Tue Nov 5 2019" "Version 1.0" "RWA3-Group1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GROUP-1/src/LandBasedWheeled/landbasedwheeled.h
.SH SYNOPSIS
.br
.PP
\fC#include 'landbasedrobot\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBrpg::LandBasedWheeled\fP"
.br
.RI "This is a concrete class containing attributes and methods for landbased wheeled navigation and handling of objects\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBrpg\fP"
.br
.RI "Namespace::rpg\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RWA3-Group1 from the source code\&.
