.TH "rpg" 3 "Tue Nov 5 2019" "Version 1.0" "RWA3-Group1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rpg \- Namespace::rpg\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLandBasedRobot\fP"
.br
.RI "This is an abstract class containing attributes and methods for landbased navigation and handling of objects\&. "
.ti -1c
.RI "class \fBLandBasedTracked\fP"
.br
.RI "This is a concrete class containing attributes and methods for landbased tracked navigation and handling of objects\&. "
.ti -1c
.RI "class \fBLandBasedWheeled\fP"
.br
.RI "This is a concrete class containing attributes and methods for landbased wheeled navigation and handling of objects\&. "
.in -1c
.SH "Detailed Description"
.PP 
Namespace::rpg\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for RWA3-Group1 from the source code\&.
