.TH "GROUP-1/src/LandBasedRobot/landbasedrobot.h" 3 "Tue Nov 5 2019" "Version 1.0" "RWA3-Group1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GROUP-1/src/LandBasedRobot/landbasedrobot.h
.SH SYNOPSIS
.br
.PP
\fC#include <strclTabCtrling\&.h>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBrpg::LandBasedRobot\fP"
.br
.RI "This is an abstract class containing attributes and methods for landbased navigation and handling of objects\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBrpg\fP"
.br
.RI "Namespace::rpg\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
GROUP 1 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0
.RE
.PP
.SH "LICENSE"
.PP
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version\&. 
.PP
Definition in file \fBlandbasedrobot\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for RWA3-Group1 from the source code\&.
