.TH "GROUP-1/src/LandBasedTracked/landbasedtracked.cpp" 3 "Tue Nov 5 2019" "Version 1.0" "RWA3-Group1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GROUP-1/src/LandBasedTracked/landbasedtracked.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'landbasedtracked\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <iostream>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for RWA3-Group1 from the source code\&.
